// src/tests/media_compat.rs
// P2.3 — the media compatibility matrix.
//
// THE QUESTION: for each codec/container the audit names, can this engine
// import the file, decode it, seek in it, and report metadata the render path
// can act on?
//
// WHAT IS COVERED, per fixture:
//
//   Import   — `Demuxer::open` finds a video stream and reports its dimensions,
//              frame rate and timebase.
//   Decode   — `Decoder::open_sw` + `decode_into`/`drain_into` yield frames whose
//              size matches the container's, in a `FrameLayout` the upload path
//              understands.
//   Seek     — `Demuxer::seek` + `Decoder::seek_to` land at or before the target
//              and then decode.
//   Timeline — the file registers in a `SourceRegistry` with the stream info a
//              `VideoStreamInfo` needs, which is what the scheduler reads.
//
// Preview and export are NOT re-tested here: `tests::export_validation` already
// drives the real `ExportEngine` end-to-end and asserts decoded pixels, and
// preview shares that render graph. What no other test covers is the DEMUX and
// DECODE front end against codecs this crate cannot itself write — VP9, AV1,
// ProRes and DNxHR — which is exactly where an import matrix earns its keep.
//
// FIXTURES ARE GENERATED BY THE `ffmpeg` BINARY, and that is a deliberate
// departure from `tests::colour_plumbing`'s rule of using the crate's own
// encoder. The reason is the opposite of that file's: there, the fixture's
// colour TAG had to agree with its SAMPLES, so only our own encoder could be
// trusted. Here the entire point is to read formats this crate has no encoder
// for, so an external writer is the only option — and using the same tool a user
// would is the honest version of "can we import what people actually have".
//
// A MISSING `ffmpeg` IS A PRINTED SKIP, NEVER A PASS. `NEXIR_REQUIRE_COMPAT=1`
// turns the skip into a failure, for a machine that is supposed to have it. The
// same applies per-fixture: a codec this ffmpeg build cannot encode is reported
// as not-exercised rather than quietly dropped, because a matrix that silently
// shrinks to H.264 is worse than no matrix.
//
// The matrix itself requires the FFmpeg shared libraries like the rest of
// src/tests/, but NO GPU and NO CUDA: it is all demux/decode on the CPU.
// **`the_last_frame_of_a_clip_is_reachable_through_the_io_layer` is the exception**
// — it drives `IoLayer`, which owns a `FrameSlotPool` and (on the interop half) a
// `CudaContext`, so it needs a headless wgpu device and skips its interop half with
// a printed reason on a host without CUDA/NVDEC.

#[cfg(test)]
mod media_compat {
    use crate::io::decoder::{DecodeError, Decoder};
    use crate::io::demuxer::Demuxer;
    use crate::timeline::rational::Rational;
    use std::path::{Path, PathBuf};
    use std::process::Command;

    const TB: Rational = Rational { num: 1, den: 90_000 };

    /// Fixture geometry. Small and even so 4:2:0 chroma is legal and every
    /// encode finishes in well under a second.
    const W: u32 = 320;
    const H: u32 = 240;
    /// Fixture length in seconds at 30 fps — 60 frames, enough that seeking to
    /// the middle is a real seek rather than a rewind to the first keyframe.
    const SECONDS: u32 = 2;
    const FPS: u32 = 30;

    /// One row of the matrix.
    struct Fixture {
        /// Short name, used for the file stem and every failure message.
        label: &'static str,
        /// Output file extension, which is what selects the container.
        ext: &'static str,
        /// ffmpeg arguments describing the codec.
        args: &'static [&'static str],
        /// Why this row exists — printed with the result so a skip is legible.
        why: &'static str,
    }

    /// The matrix the audit asks for: H.264, H.265, VP9, AV1, ProRes and
    /// DNxHD/DNxHR, across MP4, MOV, MKV and WebM.
    ///
    /// Codec and container are crossed rather than paired one-to-one where the
    /// pairing is load-bearing: H.264 appears in MP4, MOV and MKV because the
    /// three demuxers report timestamps and extradata differently, and VP9
    /// appears in both WebM and MKV because WebM is a constrained Matroska and
    /// FFmpeg selects a different demuxer name for it.
    ///
    /// ProRes and DNxHR are 4:2:2 10-bit and 4:2:2 8-bit respectively — neither
    /// is 4:2:0, so both take the decoder's swscale CONVERSION path rather than
    /// its passthrough, which no other fixture in the tree exercises.
    const FIXTURES: &[Fixture] = &[
        Fixture {
            label: "h264_mp4",
            ext:   "mp4",
            args:  &["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "the baseline: 4:2:0 8-bit in the commonest container",
        },
        Fixture {
            label: "h264_mov",
            ext:   "mov",
            args:  &["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "same bitstream, QuickTime container — a different demuxer",
        },
        Fixture {
            label: "h264_mkv",
            ext:   "mkv",
            args:  &["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "same bitstream, Matroska — timestamps in ms, not 90 kHz",
        },
        Fixture {
            label: "h265_mp4",
            ext:   "mp4",
            args:  &["-c:v", "libx265", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "HEVC, whose extradata (hvcC) differs from H.264's avcC",
        },
        Fixture {
            label: "vp9_webm",
            ext:   "webm",
            args:  &["-c:v", "libvpx-vp9", "-pix_fmt", "yuv420p", "-crf", "30", "-b:v", "0"],
            why:   "VP9 in WebM — no extradata at all, and an alt-ref frame model",
        },
        Fixture {
            label: "vp9_mkv",
            ext:   "mkv",
            args:  &["-c:v", "libvpx-vp9", "-pix_fmt", "yuv420p", "-crf", "30", "-b:v", "0"],
            why:   "VP9 in full Matroska rather than the WebM subset",
        },
        Fixture {
            label: "av1_mkv",
            ext:   "mkv",
            args:  &["-c:v", "libsvtav1", "-pix_fmt", "yuv420p", "-crf", "40"],
            why:   "AV1, the newest codec the decoder must not choke on",
        },
        Fixture {
            label: "prores_mov",
            ext:   "mov",
            args:  &["-c:v", "prores_aw", "-profile:v", "2", "-pix_fmt", "yuv422p10le"],
            why:   "4:2:2 TEN-BIT — takes the swscale conversion path, not passthrough",
        },
        Fixture {
            label: "dnxhr_mov",
            ext:   "mov",
            args:  &["-c:v", "dnxhd", "-profile:v", "dnxhr_lb", "-pix_fmt", "yuv422p"],
            why:   "4:2:2 8-bit intra — also a conversion, at a different depth",
        },
    ];

    /// Whether `NEXIR_REQUIRE_COMPAT` demands that everything actually run.
    fn require() -> bool {
        std::env::var("NEXIR_REQUIRE_COMPAT")
            .map(|v| v != "0" && !v.is_empty())
            .unwrap_or(false)
    }

    /// Locate an `ffmpeg` binary, or explain why the matrix cannot run.
    ///
    /// Delegates to [`crate::bench_media::ffmpeg_binary`], which is the single
    /// locator for the tree — `src/bin/bench.rs` needs the same one and cannot see
    /// a `#[cfg(test)]` module, so the implementation moved there rather than
    /// being duplicated. The `NEXIR_FFMPEG` override and the "missing ffmpeg is a
    /// printed skip, never a pass" contract are unchanged.
    fn ffmpeg_binary() -> Option<PathBuf> {
        crate::bench_media::ffmpeg_binary()
    }

    /// A scratch directory unique to this process, so two concurrent `cargo test`
    /// runs cannot share fixtures.
    fn scratch_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("nexir_compat_{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("failed to create the fixture directory");
        dir
    }

    /// Encode one fixture with `ffmpeg`, returning its path.
    ///
    /// `Err(reason)` means this ffmpeg build cannot produce that codec — a
    /// per-row skip, not a failure, unless `NEXIR_REQUIRE_COMPAT` is set. The
    /// distinction matters: "your ffmpeg lacks libsvtav1" is a property of the
    /// host, whereas "we could not decode the AV1 file we just wrote" is a
    /// property of this crate, and only the second should fail the suite.
    fn write_fixture(ffmpeg: &Path, dir: &Path, f: &Fixture) -> Result<PathBuf, String> {
        let out = dir.join(format!("{}.{}", f.label, f.ext));
        let _ = std::fs::remove_file(&out);

        // `testsrc2` rather than a flat colour: it has motion and detail, so an
        // inter-frame codec produces real P/B frames and a seek has something to
        // land on.  Pixel VALUES are deliberately not asserted anywhere in this
        // file — `export_validation` owns pixel correctness, and asserting it
        // here would mean re-deriving each codec's own loss.
        let source = format!("testsrc2=size={W}x{H}:rate={FPS}:duration={SECONDS}");

        let mut cmd = Command::new(ffmpeg);
        cmd.args(["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i"])
            .arg(&source)
            .args(f.args)
            .arg(&out);

        let output = cmd
            .output()
            .map_err(|e| format!("could not run ffmpeg: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!(
                "ffmpeg could not encode it ({}): {}",
                output.status,
                stderr.lines().last().unwrap_or("(no stderr)").trim()
            ));
        }
        let size = std::fs::metadata(&out)
            .map_err(|e| format!("ffmpeg reported success but the file is unreadable: {e}"))?
            .len();
        if size < 1024 {
            return Err(format!("ffmpeg produced an implausible {size}-byte file"));
        }
        Ok(out)
    }

    /// What one fixture's import + decode reported.
    struct Probed {
        /// Frames obtained, in decode order.
        frames: usize,
        /// PTS of each decoded frame, in the order the decoder emitted them.
        pts: Vec<i64>,
        /// Dimensions the container advertised.
        container_size: (u32, u32),
        /// Dimensions the decoder actually produced.
        decoded_size: (u32, u32),
        /// The layout the decoder wrote, which is what `YuvUploadNode` keys off.
        layout: crate::timeline::source::FrameLayout,
        /// The resolved colour description.
        color: crate::timeline::source::ColorInfo,
        /// Frame rate the container reported, if any.
        frame_rate: Option<Rational>,
    }

    /// Decode up to `max` frames of `path` with this crate's own demuxer/decoder.
    ///
    /// Software decode (`open_sw`): a hardware decoder would hand back NV12 or an
    /// opaque CUDA surface, so the layout assertions would describe the GPU rather
    /// than the file. The import path being tested is the same either way.
    ///
    /// The drain loop is not optional. `open_sw` enables frame-level threading
    /// (`avcodec_set_thread_count(ctx, 0)`), which holds back roughly one frame
    /// per core — a 60-frame fixture can yield nothing at all from the
    /// send/receive loop on a machine with enough cores.
    fn probe_decode(path: &Path, max: usize) -> Result<Probed, String> {
        let mut demuxer =
            Demuxer::open(path).map_err(|e| format!("Demuxer::open failed: {e:?}"))?;
        let stream = demuxer
            .video_stream
            .clone()
            .ok_or_else(|| "the container reports no video stream".to_string())?;

        let cw = stream.width.ok_or("the stream has no width")?;
        let ch = stream.height.ok_or("the stream has no height")?;

        let mut decoder = Decoder::open_sw(&stream, stream.codecpar)
            .map_err(|e| format!("Decoder::open_sw failed: {e:?}"))?;

        // Room for 4:4:4 16-bit at this size, so no fixture's format can overflow
        // the staging buffer regardless of what the decoder chooses.
        let mut buf = vec![0u8; (cw as usize * ch as usize) * 6 + 256];

        let mut pts = Vec::new();
        let mut last: Option<(crate::timeline::source::FrameLayout,
                             crate::timeline::source::ColorInfo,
                             (u32, u32))> = None;

        while pts.len() < max {
            match demuxer.next_video_packet() {
                Ok(Some(pkt)) => match decoder.decode_into(&pkt, &mut buf, None) {
                    Ok(Some(frame)) => {
                        pts.push(frame.pts);
                        last = Some((frame.meta.layout, frame.meta.color,
                                     (frame.width, frame.height)));
                    }
                    Ok(None) => continue,
                    Err(e) => return Err(format!("decode_into failed: {e:?}")),
                },
                Ok(None) => break,
                Err(e) => return Err(format!("next_video_packet failed: {e:?}")),
            }
        }
        while pts.len() < max {
            match decoder.drain_into(&mut buf) {
                Ok(Some(frame)) => {
                    pts.push(frame.pts);
                    last = Some((frame.meta.layout, frame.meta.color,
                                 (frame.width, frame.height)));
                }
                Ok(None) => break,
                Err(e) => return Err(format!("drain_into failed: {e:?}")),
            }
        }

        let (layout, color, decoded_size) =
            last.ok_or("the file produced no decodable frames")?;

        Ok(Probed {
            frames: pts.len(),
            pts,
            container_size: (cw, ch),
            decoded_size,
            layout,
            color,
            frame_rate: stream.frame_rate,
        })
    }

    /// Seek to roughly the middle of `path` and decode one frame there.
    ///
    /// Returns `(landed, target, stream_timebase)`, all in the STREAM's own
    /// timebase, so the caller can rescale the landing into project ticks without
    /// reopening the file — `Demuxer` implements `Drop`, so its `video_stream`
    /// cannot be moved out of a temporary.
    ///
    /// `seek_to` is documented to return the first frame at or after the target,
    /// so the caller asserts a bound rather than equality: a seek goes to a
    /// keyframe and then scans forward, and demanding an exact landing would be
    /// asserting that every fixture has a keyframe at that instant.
    fn probe_seek(path: &Path, target_pts: i64) -> Result<(i64, i64, Rational), String> {
        let mut demuxer =
            Demuxer::open(path).map_err(|e| format!("Demuxer::open failed: {e:?}"))?;
        let stream = demuxer
            .video_stream
            .clone()
            .ok_or_else(|| "no video stream".to_string())?;
        let stream_tb = stream.time_base;
        let mut decoder = Decoder::open_sw(&stream, stream.codecpar)
            .map_err(|e| format!("Decoder::open_sw failed: {e:?}"))?;

        let stream_target = demuxer
            .seek(target_pts, TB)
            .map_err(|e| format!("Demuxer::seek failed: {e:?}"))?;

        match decoder.seek_to(&mut demuxer, stream_target) {
            Ok(landed) => Ok((landed, stream_target, stream_tb)),
            // `NoFrame` means the discard loop hit EOF before the target.  For a
            // fixture whose middle is comfortably inside its duration that is a
            // real failure, so it is reported rather than swallowed.
            Err(DecodeError::NoFrame) => Err(format!(
                "seek_to reached EOF before the target ({stream_target} in stream \
                 ticks) — the seek overshot the file"
            )),
            Err(e) => Err(format!("seek_to failed: {e:?}")),
        }
    }

    /// P2.3 — every codec/container in the matrix must import, decode and seek.
    ///
    /// One test rather than nine, because the fixtures share an ffmpeg probe and a
    /// scratch directory and the interesting output is the TABLE: a per-row PASS or
    /// SKIP line, then a summary. Nine separate tests would each pay for the
    /// ffmpeg lookup and would report a missing encoder nine times.
    ///
    /// Asserted per row that actually ran:
    ///
    /// * **Import** — the container reports the geometry it was written with, and a
    ///   frame rate.
    /// * **Decode** — at least most of the frames come back, at the size the
    ///   container advertised, in a layout `YuvUploadNode` understands (8-bit
    ///   planar, 10-bit planar, NV12 or P010 — never something the upload path
    ///   would silently mis-stride).
    /// * **Timestamps** — PTS is strictly increasing in DECODE order for the
    ///   intra-only codecs and non-decreasing overall. Reordering codecs legally
    ///   emit frames in presentation order after the decoder reorders them, so the
    ///   strict form is asserted only where it is guaranteed.
    /// * **Seek** — landing within a reasonable window of the request rather than
    ///   at zero, which is what a seek that silently rewound to the first keyframe
    ///   would produce.
    /// * **Timeline registration** — the file goes into a `SourceRegistry` with
    ///   `VideoStreamInfo` the scheduler can read back.
    ///
    /// NOT asserted: pixel values. `export_validation` owns that end-to-end, and
    /// deriving per-codec expected pixels here would mean encoding this test's
    /// tolerance to nine different codecs' loss characteristics.
    #[test]
    fn media_compatibility_matrix_imports_decodes_and_seeks() {
        use crate::timeline::source::{
            PixelFormat, SourceRegistry, VideoRotation, VideoStreamInfo,
        };

        let ffmpeg = match ffmpeg_binary() {
            Some(p) => p,
            None => {
                let reason = "no `ffmpeg` binary on PATH (set NEXIR_FFMPEG to \
                              point at one). The linked FFmpeg DLLs do not imply \
                              the CLI is installed.";
                assert!(
                    !require(),
                    "NEXIR_REQUIRE_COMPAT is set but {reason}"
                );
                eprintln!(
                    "[media_compat] SKIP the whole matrix: {reason} No codec or \
                     container was exercised."
                );
                return;
            }
        };

        let dir = scratch_dir();
        let expected_frames = (SECONDS * FPS) as usize;

        let mut ran = 0usize;
        let mut skipped: Vec<(&str, String)> = Vec::new();

        for f in FIXTURES {
            let path = match write_fixture(&ffmpeg, &dir, f) {
                Ok(p) => p,
                Err(why) => {
                    assert!(
                        !require(),
                        "NEXIR_REQUIRE_COMPAT is set but the {} fixture could not \
                         be created: {why}",
                        f.label
                    );
                    eprintln!(
                        "[media_compat] SKIP {:<11} ({}) — {why}. This codec was \
                         NOT exercised.",
                        f.label, f.ext
                    );
                    skipped.push((f.label, why));
                    continue;
                }
            };

            // ── Import + decode ─────────────────────────────────────────────────
            // `expected_frames + 8` so a decoder that emits MORE frames than the
            // file holds is visible as an over-count rather than silently capped.
            let probed = probe_decode(&path, expected_frames + 8)
                .unwrap_or_else(|e| {
                    panic!(
                        "{}: {} — this crate could not read a file its own \
                         linked FFmpeg just wrote, so the format is genuinely \
                         unsupported on the import path. Fixture kept at {}",
                        f.label, e, path.display()
                    )
                });

            assert_eq!(
                probed.container_size, (W, H),
                "{}: the container reports {:?} but the fixture was written at \
                 {W}x{H}",
                f.label, probed.container_size
            );
            assert_eq!(
                probed.decoded_size, (W, H),
                "{}: the decoder produced {:?} frames from a {W}x{H} file — the \
                 upload path would read the wrong stride",
                f.label, probed.decoded_size
            );
            assert!(
                probed.frame_rate.is_some(),
                "{}: the container reported no frame rate, so the scheduler has \
                 nothing to quantise source timestamps against",
                f.label
            );

            // Frame count: allow a shortfall of one, because a codec with an
            // open GOP can legitimately drop a leading frame the container
            // describes, but not a wholesale loss.
            assert!(
                probed.frames + 1 >= expected_frames && probed.frames <= expected_frames + 1,
                "{}: decoded {} frame(s) from a {SECONDS}s {FPS} fps file, \
                 expected {expected_frames} — frames are being lost or duplicated \
                 on import",
                f.label, probed.frames
            );

            // Layout the upload path can actually consume.  This is the assertion
            // that catches a 4:2:2 or 4:4:4 source falling through
            // `frame_layout_for_pix_fmt` into a format `YuvUploadNode` would
            // mis-stride: the decoder is supposed to convert those to planar 4:2:0
            // at the source's own depth.
            let l = probed.layout;
            assert!(
                matches!(l.bit_depth, 8 | 10 | 12),
                "{}: the decoder reported a {}-bit layout, which no upload path \
                 handles",
                f.label, l.bit_depth
            );
            assert!(
                l.bit_depth > 8 || !l.msb_aligned,
                "{}: an 8-bit layout cannot be MSB-aligned",
                f.label
            );

            // ── Timestamps ──────────────────────────────────────────────────────
            assert!(
                !probed.pts.is_empty(),
                "{}: no timestamps were recorded",
                f.label
            );
            for (i, w) in probed.pts.windows(2).enumerate() {
                assert!(
                    w[1] >= w[0],
                    "{}: PTS went backwards between decoded frames {i} and {}: \
                     {} then {}. The decoder emits frames in PRESENTATION order, \
                     so this is not B-frame reordering — it is a timestamp bug.",
                    f.label, i + 1, w[0], w[1]
                );
            }
            let distinct = {
                let mut v = probed.pts.clone();
                v.sort_unstable();
                v.dedup();
                v.len()
            };
            assert_eq!(
                distinct, probed.pts.len(),
                "{}: {} of {} decoded frames share a timestamp — the timeline \
                 would collapse them onto the same instant",
                f.label, probed.pts.len() - distinct, probed.pts.len()
            );

            // ── Seek ────────────────────────────────────────────────────────────
            // Target the middle of the file in project ticks.
            let mid_pts = (SECONDS as i64 * TB.den) / 2;
            let (landed, target, stream_tb) = probe_seek(&path, mid_pts)
                .unwrap_or_else(|e| panic!("{}: {}", f.label, e));
            assert!(
                landed >= target,
                "{}: seek_to returned {landed} for a target of {target} — it is \
                 documented to return the first frame at or AFTER the target",
                f.label
            );
            // Landing must be near the request, not back at the start.  One
            // second of slack covers any keyframe interval these fixtures use
            // (x264 defaults to 250, but a 60-frame file has one GOP, so the
            // forward scan does the work).
            let landed_project = stream_tb.rescale_pts(landed, TB);
            assert!(
                (landed_project - mid_pts).abs() <= TB.den,
                "{}: a seek to {:.3}s landed at {:.3}s — more than a second away, \
                 which is a seek that rewound rather than one that scanned forward",
                f.label,
                mid_pts as f64 / TB.den as f64,
                landed_project as f64 / TB.den as f64
            );

            // ── Timeline registration ───────────────────────────────────────────
            // The last hop before the scheduler: the file has to become a
            // `VideoStreamInfo` that reads back intact.
            let mut reg = SourceRegistry::new();
            let id = reg.register(
                path.clone(),
                Some(VideoStreamInfo {
                    width:        probed.container_size.0,
                    height:       probed.container_size.1,
                    frame_rate:   probed.frame_rate.unwrap(),
                    pixel_fmt:    if l.bit_depth > 8 {
                        PixelFormat::Yuv420p10
                    } else {
                        PixelFormat::Yuv420p
                    },
                    color_info:   probed.color,
                    duration_pts: SECONDS as i64 * TB.den,
                    is_vfr:       false,
                    time_base:    TB,
                    rotation:     VideoRotation::None,
                }),
                None,
            );
            let info = reg
                .video_info(id)
                .unwrap_or_else(|e| panic!("{}: video_info failed: {e:?}", f.label));
            assert_eq!(
                (info.width, info.height), (W, H),
                "{}: the registry round-tripped the wrong dimensions",
                f.label
            );
            assert!(
                reg.is_available(id),
                "{}: a file that exists on disk registered as unavailable",
                f.label
            );
            // `ColorInfo` must be fully resolved by the time it is stored — an
            // `Unknown` reaching the render graph is what `luma_coefficients`
            // silently defaults to BT.709.
            assert_ne!(
                info.color_info.effective_matrix(W, H),
                crate::timeline::source::MatrixCoefficients::Unknown,
                "{}: the stored colour matrix is still Unknown",
                f.label
            );

            eprintln!(
                "[media_compat] PASS {:<11} {:>4}  {} frame(s), {}x{}, {:?}, \
                 {}-bit{}, matrix {:?}, seek {:.3}s→{:.3}s   [{}]",
                f.label, f.ext, probed.frames, W, H,
                probed.frame_rate.unwrap(),
                l.bit_depth,
                if l.semi_planar { " semi-planar" } else { " planar" },
                info.color_info.effective_matrix(W, H),
                mid_pts as f64 / TB.den as f64,
                landed_project as f64 / TB.den as f64,
                f.why,
            );
            ran += 1;
            let _ = std::fs::remove_file(&path);
        }

        eprintln!(
            "[media_compat] matrix: {ran}/{} row(s) exercised",
            FIXTURES.len()
        );
        for (label, why) in &skipped {
            eprintln!("[media_compat]   not exercised: {label} — {why}");
        }
        let _ = std::fs::remove_dir_all(&dir);

        // H.264/MP4 is the one row whose absence means something is wrong with the
        // host rather than with an exotic codec: every ffmpeg build has libx264 or
        // an equivalent, and this crate's own export tests write H.264/MP4.
        assert!(
            ran > 0,
            "not one row of the compatibility matrix ran, though ffmpeg was found \
             — the fixture generation is broken rather than a codec being missing"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TASK G3 — THE LAST FRAMES OF A CLIP MUST BE REACHABLE
    //
    // `IoLayer::decode_blocking` used never to drain the decoder, so FFmpeg's
    // frame-level threading (and NVDEC's own delay) held back roughly one frame
    // per core and the last frames of every file were unreachable through the
    // engine — measured: frame 57 of a 60-frame `cam_4k30`.
    //
    // **The symptom is a plausible-looking frame, which is why this needs a test
    // rather than a run.** `decode_blocking`'s `!decoded_anything` arm falls back
    // to whatever `FrameCache` holds for the previous position, so the playhead
    // moves over the last second while the picture freezes: no error, no warning,
    // and a `Some(frame)` return either way. `bench --interop` found it only
    // because a one-frame interop target has no cache to fall back on.
    //
    // Both tests below therefore assert on WHERE THE FRAME CAME FROM, not merely
    // that one came back: a fresh decode inserts the frame under the pts that was
    // asked for, and the stale fallback returns an entry keyed at the PREVIOUS
    // pts. `cache.get(source, wanted_pts)` is the only observable that separates
    // them — `decode_blocking` hands back a slot id and metadata, not a pts.
    // ─────────────────────────────────────────────────────────────────────────

    /// Write one H.264/MP4 fixture at an arbitrary frame rate and length.
    ///
    /// Separate from [`write_fixture`] because the two G3 tests need geometries the
    /// matrix does not: a short clip whose tail is inside the decoder's delay, and
    /// a HIGH-frame-rate clip where 600 video packets fit inside the five seconds
    /// `decode_blocking` will read forward over without seeking.
    fn write_timed_fixture(
        ffmpeg: &Path,
        dir: &Path,
        label: &str,
        fps: u32,
        seconds: u32,
    ) -> Result<PathBuf, String> {
        let out = dir.join(format!("{label}.mp4"));
        let _ = std::fs::remove_file(&out);
        let source = format!("testsrc2=size={W}x{H}:rate={fps}");
        let status = Command::new(ffmpeg)
            .args(["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-t"])
            .arg(seconds.to_string())
            .arg("-i")
            .arg(&source)
            .args(["-c:v", "libx264", "-preset", "veryfast", "-crf", "24", "-pix_fmt", "yuv420p"])
            .arg(&out)
            .output()
            .map_err(|e| format!("could not run ffmpeg: {e}"))?;
        if !status.status.success() {
            return Err(format!(
                "ffmpeg could not encode the {label} fixture: {}",
                String::from_utf8_lossy(&status.stderr).trim()
            ));
        }
        Ok(out)
    }

    /// An `IoLayer` over one file, with the interop registry the caller chooses.
    ///
    /// `interop` is a parameter for the same reason `build_multi_clip_harness`'s is:
    /// the CPU-path test must be on `disabled` so it cannot accidentally measure
    /// NVDEC's delay instead of the software decoder's, and the interop test must
    /// be on a live registry because the fallback it is checking only exists there.
    fn io_layer_over(
        device: &std::sync::Arc<crate::render::device::GpuDevice>,
        path: &Path,
        fps: Rational,
        duration_pts: i64,
        interop: std::sync::Arc<crate::io::interop_decode::InteropDecodeTargets>,
    ) -> (
        std::sync::Arc<crate::io::io_layer::IoLayer>,
        crate::timeline::ids::SourceId,
        std::sync::mpsc::Receiver<crate::io::prefetch::PrefetchRequest>,
    ) {
        use crate::io::frame_cache::FrameCache;
        use crate::io::io_layer::IoLayer;
        use crate::io::slot_pool::FrameSlotPool;
        use crate::timeline::source::{
            ColorInfo, PixelFormat, SourceRegistry, VideoRotation, VideoStreamInfo,
        };

        let sources = std::sync::Arc::new(std::sync::RwLock::new(SourceRegistry::new()));
        let source_id = sources.write().unwrap().register(
            path.to_path_buf(),
            Some(VideoStreamInfo {
                width: W,
                height: H,
                frame_rate: fps,
                pixel_fmt: PixelFormat::Yuv420p,
                color_info: ColorInfo::bt709(),
                duration_pts,
                is_vfr: false,
                time_base: TB,
                rotation: VideoRotation::None,
            }),
            None,
        );

        let pool = std::sync::Arc::new(FrameSlotPool::new(device));
        let cache = std::sync::Arc::new(FrameCache::new(std::sync::Arc::clone(&pool), 32));
        // The receiver is returned rather than dropped: `get_or_decode` sends
        // prefetch requests, and a disconnected channel would make those fail
        // silently. No worker is spawned — these tests call `decode_blocking`
        // directly, and a background thread decoding the same source would race the
        // decoder position the tests are asserting about.
        let (tx, rx) = std::sync::mpsc::sync_channel(16);
        let io = std::sync::Arc::new(IoLayer::new(
            std::sync::Arc::clone(&device.device),
            pool,
            cache,
            sources,
            tx,
            TB,
            interop,
        ));
        (io, source_id, rx)
    }

    /// G3 — the last frames of a clip must come back FRESH, on the CPU path.
    ///
    /// Walks the whole clip in order, the way playback does, because approaching the
    /// tail is the only way to reach it: a cold request for the last frame seeks
    /// first, and `Decoder::seek_to`'s own discard loop hits EOF before the target
    /// and returns `NoFrame` — a different failure, in a different function, that
    /// the drain does not address.
    ///
    /// The assertion is on the LAST EIGHT frames rather than only the final one:
    /// the decoder holds back roughly one frame per core (12 here), so a one-frame
    /// assertion could pass on a machine whose delay happens to be zero.
    #[test]
    fn the_last_frames_of_a_clip_are_reachable_through_the_io_layer() {
        use crate::timeline::rational::frame_to_pts;

        let Some(ffmpeg) = ffmpeg_binary() else {
            assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but there is no ffmpeg");
            eprintln!("[media_compat] SKIP the G3 drain test: no `ffmpeg` binary.");
            return;
        };
        let dir = scratch_dir();
        let fps = Rational { num: FPS as i64, den: 1 };
        let frames = (FPS * SECONDS) as usize;
        let path = match write_timed_fixture(&ffmpeg, &dir, "g3_tail", FPS, SECONDS) {
            Ok(p) => p,
            Err(why) => {
                assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but {why}");
                eprintln!("[media_compat] SKIP the G3 drain test: {why}");
                return;
            }
        };

        let device = std::sync::Arc::new(
            pollster::block_on(crate::render::device::GpuDevice::new_headless())
                .expect("headless GpuDevice"),
        );
        let (io, sid, _rx) = io_layer_over(
            &device,
            &path,
            fps,
            frames as i64 * (TB.den / FPS as i64),
            // `disabled`, deliberately: this test is about the CPU path's drain, and
            // a live registry would put NVDEC's delay in front of it instead.
            std::sync::Arc::new(crate::io::interop_decode::InteropDecodeTargets::disabled(
                std::sync::Arc::clone(&device),
            )),
        );

        let mut served = 0usize;
        let mut fresh = 0usize;
        let mut first_stale: Option<usize> = None;
        for i in 0..frames {
            let pts = frame_to_pts(i as i64, fps, TB);
            if io.decode_blocking(sid, pts).is_some() {
                served += 1;
            }
            // FRESH means the frame was decoded for THIS pts and inserted under it.
            // The stale fallback returns an entry keyed at the previous position, so
            // this key is absent — which is the whole difference the drain makes.
            if io.cache.get(sid, pts).is_some() {
                fresh += 1;
            } else if first_stale.is_none() {
                first_stale = Some(i);
            }
        }

        eprintln!(
            "[media_compat] G3: {served}/{frames} frame(s) served, {fresh} of them freshly \
             decoded{}",
            first_stale
                .map(|i| format!(", first stale at frame {i}"))
                .unwrap_or_default()
        );

        assert_eq!(
            served, frames,
            "the engine returned nothing at all for {} of {frames} frame(s)",
            frames - served
        );
        // The tail is what the drain exists for. Eight frames is comfortably inside
        // `FrameCache`'s 32 slots, so a fresh entry cannot have been evicted, and
        // comfortably below the decoder's own delay on any multi-core host.
        let tail_start = frames - 8;
        for i in tail_start..frames {
            let pts = frame_to_pts(i as i64, fps, TB);
            assert!(
                io.cache.get(sid, pts).is_some(),
                "frame {i} of {frames} was served from the previous position rather than \
                 decoded: the decoder is holding it back and nothing drained it. The \
                 playhead moves while the picture freezes, and `decode_blocking` returns \
                 Some(_) either way — first stale frame this run was {first_stale:?}"
            );
        }
        // And the whole run, not just the tail: every frame of a sequential walk is
        // either read forward to or drained, so a stale one ANYWHERE is a defect.
        // Freshness is sampled immediately after each decode, so `FrameCache`'s
        // 32-slot capacity cannot make this flaky on a longer fixture.
        assert_eq!(
            fresh, frames,
            "{} frame(s) of a sequential walk were served from the previous position \
             (first at {first_stale:?}) — every frame here is reachable by reading \
             forward or by draining",
            frames - fresh
        );

        let _ = std::fs::remove_file(&path);
    }

    /// G3 — a COLD request must serve the frame it asked for, not the next one.
    ///
    /// **This is the assertion the rest of the file could not make**, and the reason
    /// the seek defect survived every other test: `decode_blocking` caches whatever
    /// it decoded under the pts that was REQUESTED, so `cache.get(source, pts)`
    /// answers `Some` for the wrong picture just as readily as for the right one.
    /// Freshness proves a decode happened, never which frame it produced.
    ///
    /// What it catches: `Decoder::seek_to` decodes until it reaches the target,
    /// **discards that frame** and returns its pts — so a cold request for frame N
    /// was answered with frame N+1, and every sequential request after it inherited
    /// the shift. The tail was the only visible symptom (there is no N+1 for the
    /// last frame), which is why this read as one stale frame rather than as sixty
    /// wrong ones.
    ///
    /// Method: decode the whole fixture once through a plain `Demuxer` + `Decoder`
    /// to get each frame's luma plane in presentation order, then ask a FRESH
    /// `IoLayer` (fresh decoder ⇒ `prev_pts == i64::MIN` ⇒ the seek branch) for one
    /// frame at a time and compare what lands in the slot against that reference.
    ///
    /// **The reference must come from outside `IoLayer`.** Comparing a cold request
    /// against a sequential walk of the same `IoLayer` would have passed while the
    /// bug was live: the walk's first request seeks too, so both arms were shifted
    /// by one and agreed with each other. Same trap as gotcha 11's mis-tagged
    /// control and as `bench --interop`'s `Δpx`, which compares two arms that shared
    /// this defect.
    ///
    /// The reference decoder is opened with hardware enabled, exactly as `IoLayer`
    /// opens its own, so the two produce the same layout (NV12 under NVDEC, YUV420P
    /// in software) and the luma plane is the leading `W*H` bytes either way.
    #[test]
    fn a_cold_seek_serves_the_frame_that_was_asked_for() {
        use crate::timeline::rational::frame_to_pts;

        let Some(ffmpeg) = ffmpeg_binary() else {
            assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but there is no ffmpeg");
            eprintln!("[media_compat] SKIP the G3 cold-seek test: no `ffmpeg` binary.");
            return;
        };
        let dir = scratch_dir();
        let fps = Rational { num: FPS as i64, den: 1 };
        let frames = (FPS * SECONDS) as usize;
        let path = match write_timed_fixture(&ffmpeg, &dir, "g3_cold_seek", FPS, SECONDS) {
            Ok(p) => p,
            Err(why) => {
                assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but {why}");
                eprintln!("[media_compat] SKIP the G3 cold-seek test: {why}");
                return;
            }
        };

        const LUMA: usize = (W * H) as usize;

        // ── The reference: every frame's luma, in the order the decoder emits it ──
        let reference: Vec<Vec<u8>> = {
            let mut demuxer = Demuxer::open(&path).expect("Demuxer::open");
            let stream = demuxer.video_stream.clone().expect("no video stream");
            let mut decoder = Decoder::open(&stream, stream.codecpar, true)
                .expect("Decoder::open");
            let mut buf = vec![0u8; LUMA * 6 + 256];
            let mut out: Vec<Vec<u8>> = Vec::new();
            while let Ok(Some(pkt)) = demuxer.next_video_packet() {
                if let Ok(Some(_)) = decoder.decode_into(&pkt, &mut buf, None) {
                    out.push(buf[..LUMA].to_vec());
                }
            }
            // The tail lives behind the decoder's own delay, so the reference needs
            // the same drain the engine does — otherwise the last frames have no
            // reference to be compared against and the test would silently skip
            // exactly the region G3 is about.
            while let Ok(Some(_)) = decoder.drain_into(&mut buf) {
                out.push(buf[..LUMA].to_vec());
            }
            out
        };
        assert_eq!(
            reference.len(), frames,
            "the reference decode produced {} frame(s) of a {frames}-frame fixture, so \
             it cannot be a reference for the frames it is missing",
            reference.len()
        );

        /// Mean absolute difference between two luma planes, in code values.
        fn mad(a: &[u8], b: &[u8]) -> f64 {
            let total: u64 = a
                .iter()
                .zip(b)
                .map(|(x, y)| x.abs_diff(*y) as u64)
                .sum();
            total as f64 / a.len() as f64
        }

        let device = std::sync::Arc::new(
            pollster::block_on(crate::render::device::GpuDevice::new_headless())
                .expect("headless GpuDevice"),
        );
        let (io, sid, _rx) = io_layer_over(
            &device,
            &path,
            fps,
            frames as i64 * (TB.den / FPS as i64),
            std::sync::Arc::new(
                crate::io::interop_decode::InteropDecodeTargets::disabled(
                    std::sync::Arc::clone(&device),
                ),
            ),
        );

        // Frame 0 (the seek lands exactly on it), two interior frames the seek has to
        // scan forward to, and the last frame, which only the drain can reach. The
        // off-by-one is identical at each, but a single probe could be explained away
        // as a keyframe quirk.
        //
        // **DESCENDING, through ONE `IoLayer`.** Every request must take the seek
        // branch, and there are two ways to get there: a cold decoder
        // (`prev_pts == i64::MIN`) or a request BEFORE the decoder's position
        // (`pts < prev_pts`) — the same branch, and the second is what scrubbing
        // backwards does. Descending uses the second, so one layer suffices; a fresh
        // layer per probe would allocate a fresh `FrameSlotPool` per probe, which is
        // ~386 MB of staging buffers each (tier 3 alone is 2 × 49.8 MB) and OOMs the
        // test binary when the suite runs it alongside the rest.
        //
        // Requesting the last frame first also covers the seek-after-drain case for
        // free: `flush()` clears the draining flag, so the next read-forward works.
        for i in [frames - 1, 41, 17, 0] {
            let pts = frame_to_pts(i as i64, fps, TB);
            let (slot, _meta) = io
                .decode_blocking(sid, pts)
                .unwrap_or_else(|| panic!("a cold request for frame {i} returned nothing"));
            assert!(
                io.cache.get(sid, pts).is_some(),
                "a cold request for frame {i} was served from the cache rather than \
                 decoded, so this comparison would be about a stale frame"
            );
            let (got_self, got_next) = io.pool.with_buffer_read(slot, |bytes| {
                (
                    mad(&bytes[..LUMA], &reference[i]),
                    reference.get(i + 1).map(|next| mad(&bytes[..LUMA], next)),
                )
            });

            eprintln!(
                "[media_compat] G3 cold seek: frame {i:>3} — MAD vs itself {got_self:.3}, \
                 vs the next frame {}",
                got_next
                    .map(|d| format!("{d:.3}"))
                    .unwrap_or_else(|| "n/a (last frame)".into())
            );

            // Tolerant of nothing but codec noise: the reference and the engine run
            // the same decoder over the same bitstream, so the right frame is bit
            // identical in practice. A whole frame of drift is ~10 code values on
            // this fixture, well clear of 1.0.
            assert!(
                got_self < 1.0,
                "a cold request for frame {i} came back with a DIFFERENT PICTURE: \
                 mean absolute luma difference {got_self:.3} against frame {i}, \
                 {} against frame {}. `Decoder::seek_to` discards the frame it lands \
                 on, so the read-forward loop starts one frame late and the result is \
                 cached under the pts that was asked for — no error, and every \
                 freshness assertion still passes.",
                got_next
                    .map(|d| format!("{d:.3}"))
                    .unwrap_or_else(|| "n/a".into()),
                i + 1
            );
            if let Some(next) = got_next {
                assert!(
                    next > got_self,
                    "frame {i} matches frame {} at least as well as itself \
                     ({next:.3} vs {got_self:.3}) — the fixture's consecutive frames \
                     are too similar for this test to detect a one-frame shift, so it \
                     is not testing anything",
                    i + 1
                );
            }
        }

        let _ = std::fs::remove_file(&path);
    }

    /// G3 — the 600-packet bound must NOT drain, and that is a separate rule.
    ///
    /// `hit_eof` is what distinguishes "the demuxer ran dry" from "the corrupt-file
    /// guard tripped". Draining on the latter puts the decoder in draining mode,
    /// where `avcodec_send_packet` refuses all further input — so **every later
    /// frame on that source disappears until a seek flushes it**, which is a worse
    /// bug than the one the drain fixes and has the same disguise (the stale
    /// fallback keeps returning `Some`).
    ///
    /// Reaching the bound needs a request more than 600 packets ahead of the
    /// decoder that is NOT far enough ahead to seek: `decode_blocking` seeks when
    /// the gap exceeds five seconds, so the fixture is 240 fps, where five seconds
    /// is 1200 frames. At 30 fps this case is unreachable and the rule would be
    /// untestable.
    #[test]
    fn the_600_packet_bound_does_not_leave_the_decoder_draining() {
        use crate::timeline::rational::frame_to_pts;

        let Some(ffmpeg) = ffmpeg_binary() else {
            assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but there is no ffmpeg");
            eprintln!("[media_compat] SKIP the G3 bound test: no `ffmpeg` binary.");
            return;
        };
        let dir = scratch_dir();
        // 240 fps × 4 s = 960 frames, so a request 900 frames ahead is 3.75 s ahead
        // — inside the five-second no-seek window and past the 600-packet bound.
        const HZ: u32 = 240;
        const SECS: u32 = 4;
        let fps = Rational { num: HZ as i64, den: 1 };
        let path = match write_timed_fixture(&ffmpeg, &dir, "g3_bound", HZ, SECS) {
            Ok(p) => p,
            Err(why) => {
                assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but {why}");
                eprintln!("[media_compat] SKIP the G3 bound test: {why}");
                return;
            }
        };

        let device = std::sync::Arc::new(
            pollster::block_on(crate::render::device::GpuDevice::new_headless())
                .expect("headless GpuDevice"),
        );
        let total = (HZ * SECS) as usize;
        let (io, sid, _rx) = io_layer_over(
            &device,
            &path,
            fps,
            total as i64 * (TB.den / HZ as i64),
            std::sync::Arc::new(crate::io::interop_decode::InteropDecodeTargets::disabled(
                std::sync::Arc::clone(&device),
            )),
        );

        // 1. Frame 0, so the decoder has a position and the cache has an entry for
        //    the stale fallback to hand back later.
        let first = frame_to_pts(0, fps, TB);
        assert!(
            io.decode_blocking(sid, first).is_some(),
            "the fixture's first frame did not decode at all"
        );
        assert!(io.cache.get(sid, first).is_some(), "frame 0 was not cached");

        // 2. Frame 900: sequential (3.75 s ahead, under the five-second seek
        //    threshold) but more than 600 packets away, so the read-forward hits the
        //    corrupt-file bound and gives up. Expected to be served stale — the
        //    bound doing its job — and asserted so the case cannot silently stop
        //    being the case this test is about.
        let far = frame_to_pts(900, fps, TB);
        io.decode_blocking(sid, far);
        assert!(
            io.cache.get(sid, far).is_none(),
            "frame 900 decoded within 600 packets, so this test is no longer \
             exercising the corrupt-file bound at all"
        );

        // 3. A frame the decoder has ALREADY passed. With the bound left alone this
        //    is an ordinary read-forward that returns the next available frame. If
        //    the bound had drained the decoder, every send is refused, nothing
        //    decodes, and the stale fallback answers with frame 0 — `Some(_)`, and
        //    keyed at the wrong pts.
        let after = frame_to_pts(400, fps, TB);
        let got = io.decode_blocking(sid, after);
        assert!(
            got.is_some(),
            "nothing came back after the 600-packet bound tripped: the decoder was \
             left in draining mode and is refusing input"
        );
        assert!(
            io.cache.get(sid, after).is_some(),
            "the frame after the 600-packet bound was served from the previous \
             position rather than decoded — the bound put the decoder into draining \
             mode, so it refuses all further input until a seek flushes it. `hit_eof` \
             is what keeps the bound from draining."
        );

        eprintln!(
            "[media_compat] G3: the 600-packet bound left the decoder usable — a \
             later frame still decoded."
        );
        let _ = std::fs::remove_file(&path);
    }

    /// G3 step 2 — at EOF the interop path declines and the CPU path serves the
    /// tail, and that is the design rather than a gap.
    ///
    /// `decode_interop` returns `None` when the demuxer runs dry: it does not drain,
    /// because a drained frame arrives in host memory (`drain_into` passes
    /// `interop = None` to `emit_frame`) and would have to be uploaded — on the arm
    /// whose whole purpose is that nothing is uploaded. So the last frames of a clip
    /// are served by the CPU fallback, exactly as a source that fell back for any
    /// other reason is.
    ///
    /// Holds [`crate::tests::cuda_lock`] for its whole body and takes the ONE shared
    /// context (gotcha 4), and skips with a printed reason when the host has no CUDA
    /// or the decoder is not NVDEC — never a silent pass.
    #[test]
    fn at_eof_the_interop_path_declines_and_the_cpu_path_serves_the_tail() {
        use crate::timeline::rational::frame_to_pts;

        let _guard = crate::tests::cuda_lock();

        let Some(ffmpeg) = ffmpeg_binary() else {
            assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but there is no ffmpeg");
            eprintln!("[media_compat] SKIP the G3 interop-tail test: no `ffmpeg` binary.");
            return;
        };
        let dir = scratch_dir();
        let fps = Rational { num: FPS as i64, den: 1 };
        let frames = (FPS * SECONDS) as usize;
        let path = match write_timed_fixture(&ffmpeg, &dir, "g3_interop_tail", FPS, SECONDS) {
            Ok(p) => p,
            Err(why) => {
                assert!(!require(), "NEXIR_REQUIRE_COMPAT is set but {why}");
                eprintln!("[media_compat] SKIP the G3 interop-tail test: {why}");
                return;
            }
        };

        let device = std::sync::Arc::new(
            pollster::block_on(crate::render::device::GpuDevice::new_headless())
                .expect("headless GpuDevice"),
        );
        let capability = crate::interop::capability::InteropCapability::probe(&device);
        let cuda = crate::tests::shared_cuda_ctx(&capability);
        if cuda.is_none() {
            eprintln!(
                "[media_compat] SKIP the G3 interop-tail test: CUDA interop is \
                 unavailable on this host (transport={:?}), so there is no interop \
                 path to decline.",
                capability.transport
            );
            return;
        }
        let registry = std::sync::Arc::new(
            crate::io::interop_decode::InteropDecodeTargets::with_context(
                std::sync::Arc::clone(&device),
                capability,
                cuda,
            ),
        );
        let (io, sid, _rx) = io_layer_over(
            &device,
            &path,
            fps,
            frames as i64 * (TB.den / FPS as i64),
            std::sync::Arc::clone(&registry),
        );

        // Walk in order exactly as `FrameScheduler::process_island` does: interop
        // first, CPU fallback when it declines.
        let mut by_interop = 0usize;
        let mut by_cpu = 0usize;
        let mut tail_by_cpu = 0usize;
        let mut tail_cpu_fresh = 0usize;
        let mut last_frame_by_cpu = false;
        let mut last_frame_fresh = false;
        let tail_start = frames - 8;
        for i in 0..frames {
            let pts = frame_to_pts(i as i64, fps, TB);
            if io.decode_interop(sid, pts).is_some() {
                by_interop += 1;
            } else if io.decode_blocking(sid, pts).is_some() {
                by_cpu += 1;
                let fresh = io.cache.get(sid, pts).is_some();
                if i >= tail_start {
                    tail_by_cpu += 1;
                    if fresh {
                        tail_cpu_fresh += 1;
                    }
                }
                if i + 1 == frames {
                    last_frame_by_cpu = true;
                    last_frame_fresh = fresh;
                }
            }
        }

        eprintln!(
            "[media_compat] G3: {by_interop} frame(s) on the interop path, {by_cpu} on the \
             CPU fallback ({tail_cpu_fresh}/{tail_by_cpu} of the last 8 fresh), {} live \
             target(s){}",
            registry.live_targets(),
            registry
                .rejections()
                .first()
                .map(|(id, why)| format!(" — source {} fell back: {why}", id.index()))
                .unwrap_or_default(),
        );

        if registry.live_targets() == 0 {
            // Not a failure: no NVDEC on this host, or a source geometry the interop
            // path refuses. Reported rather than asserted, because the thing under
            // test does not exist here.
            eprintln!(
                "[media_compat] SKIP the interop half: no target was allocated, so \
                 every frame took the CPU path and there was nothing to decline."
            );
            return;
        }

        assert!(
            by_interop > 0,
            "a target was allocated but not one frame came back through it, so this \
             test says nothing about the interop path's behaviour at EOF"
        );
        // THE DESIGN: the tail is served, and it is served by the CPU path. Both
        // halves matter — `by_cpu == 0` would mean the interop path is somehow
        // draining (which would upload the frame it drained), and a tail that is not
        // fresh is the G3 bug with a different decoder in front of it.
        assert!(
            by_cpu > 0,
            "every frame came back through the interop path, including the tail. \
             `decode_interop` must return None at EOF (G3 step 2) — a drained frame \
             arrives in host memory and would be uploaded on the arm whose whole \
             point is that nothing is"
        );
        // **HOW MANY frames the fallback serves is a property of the host, so it is
        // not asserted; that EVERY one of them is fresh is a property of this crate,
        // so it is.**
        //
        // This assertion used to be `tail_fresh == 8`, and the 8 was never a
        // measurement of anything — it was the count that happened to hold while
        // `decode_blocking` and `decode_interop` both called `Decoder::seek_to`,
        // which discards the frame it lands on. Every request was answered one frame
        // late, so the interop arm ran out of reachable frames eight short of the end
        // and the CPU path picked up the whole tail. With that fixed (both arms now
        // flush and read forward, keeping the frame `seek_to` threw away) the interop
        // arm reaches to within the decoder's own hold-back: measured 58 of 60 here,
        // leaving 2 for the fallback. The number moves with core count and codec
        // delay, so pinning it would be pinning this machine.
        //
        // What is invariant, and what G3 is actually about: the frames the interop
        // path cannot reach must come back FRESHLY DECODED from the CPU path, never
        // out of `FrameCache` at the previous position.
        assert_eq!(
            tail_cpu_fresh, tail_by_cpu,
            "{} of the {tail_by_cpu} tail frame(s) the CPU path served came from the \
             previous position rather than being decoded — the interop arm's tail is \
             served by that fallback, so the drain has to work there too",
            tail_by_cpu - tail_cpu_fresh
        );
        // The LAST frame is the one only the drain can reach, on either arm, so it is
        // named rather than left to the count above: a tail of zero CPU frames would
        // satisfy the equality vacuously.
        assert!(
            last_frame_by_cpu,
            "the final frame came back through the interop path — `decode_interop` \
             does not drain, so it cannot have; something is serving a stale target as \
             a `Cached` hit"
        );
        assert!(
            last_frame_fresh,
            "the final frame was served from the previous position: the CPU fallback's \
             drain is what makes it reachable, and it did not run"
        );

        let _ = std::fs::remove_file(&path);
    }
}
