// src/tests/media_compat.rs
// P2.3 — the media compatibility matrix.
//
// THE QUESTION: for each codec/container the audit names, can this engine
// import the file, decode it, seek in it, and report metadata the render path
// can act on?
//
// WHAT IS COVERED, per fixture:
//
//   Import   — `Demuxer::open` finds a video stream and reports its dimensions,
//              frame rate and timebase.
//   Decode   — `Decoder::open_sw` + `decode_into`/`drain_into` yield frames whose
//              size matches the container's, in a `FrameLayout` the upload path
//              understands.
//   Seek     — `Demuxer::seek` + `Decoder::seek_to` land at or before the target
//              and then decode.
//   Timeline — the file registers in a `SourceRegistry` with the stream info a
//              `VideoStreamInfo` needs, which is what the scheduler reads.
//
// Preview and export are NOT re-tested here: `tests::export_validation` already
// drives the real `ExportEngine` end-to-end and asserts decoded pixels, and
// preview shares that render graph. What no other test covers is the DEMUX and
// DECODE front end against codecs this crate cannot itself write — VP9, AV1,
// ProRes and DNxHR — which is exactly where an import matrix earns its keep.
//
// FIXTURES ARE GENERATED BY THE `ffmpeg` BINARY, and that is a deliberate
// departure from `tests::colour_plumbing`'s rule of using the crate's own
// encoder. The reason is the opposite of that file's: there, the fixture's
// colour TAG had to agree with its SAMPLES, so only our own encoder could be
// trusted. Here the entire point is to read formats this crate has no encoder
// for, so an external writer is the only option — and using the same tool a user
// would is the honest version of "can we import what people actually have".
//
// A MISSING `ffmpeg` IS A PRINTED SKIP, NEVER A PASS. `NEXIR_REQUIRE_COMPAT=1`
// turns the skip into a failure, for a machine that is supposed to have it. The
// same applies per-fixture: a codec this ffmpeg build cannot encode is reported
// as not-exercised rather than quietly dropped, because a matrix that silently
// shrinks to H.264 is worse than no matrix.
//
// Requires the FFmpeg shared libraries like the rest of src/tests/, but NO GPU
// and NO CUDA: everything here is demux/decode on the CPU.

#[cfg(test)]
mod media_compat {
    use crate::io::decoder::{DecodeError, Decoder};
    use crate::io::demuxer::Demuxer;
    use crate::timeline::rational::Rational;
    use std::path::{Path, PathBuf};
    use std::process::Command;

    const TB: Rational = Rational { num: 1, den: 90_000 };

    /// Fixture geometry. Small and even so 4:2:0 chroma is legal and every
    /// encode finishes in well under a second.
    const W: u32 = 320;
    const H: u32 = 240;
    /// Fixture length in seconds at 30 fps — 60 frames, enough that seeking to
    /// the middle is a real seek rather than a rewind to the first keyframe.
    const SECONDS: u32 = 2;
    const FPS: u32 = 30;

    /// One row of the matrix.
    struct Fixture {
        /// Short name, used for the file stem and every failure message.
        label: &'static str,
        /// Output file extension, which is what selects the container.
        ext: &'static str,
        /// ffmpeg arguments describing the codec.
        args: &'static [&'static str],
        /// Why this row exists — printed with the result so a skip is legible.
        why: &'static str,
    }

    /// The matrix the audit asks for: H.264, H.265, VP9, AV1, ProRes and
    /// DNxHD/DNxHR, across MP4, MOV, MKV and WebM.
    ///
    /// Codec and container are crossed rather than paired one-to-one where the
    /// pairing is load-bearing: H.264 appears in MP4, MOV and MKV because the
    /// three demuxers report timestamps and extradata differently, and VP9
    /// appears in both WebM and MKV because WebM is a constrained Matroska and
    /// FFmpeg selects a different demuxer name for it.
    ///
    /// ProRes and DNxHR are 4:2:2 10-bit and 4:2:2 8-bit respectively — neither
    /// is 4:2:0, so both take the decoder's swscale CONVERSION path rather than
    /// its passthrough, which no other fixture in the tree exercises.
    const FIXTURES: &[Fixture] = &[
        Fixture {
            label: "h264_mp4",
            ext:   "mp4",
            args:  &["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "the baseline: 4:2:0 8-bit in the commonest container",
        },
        Fixture {
            label: "h264_mov",
            ext:   "mov",
            args:  &["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "same bitstream, QuickTime container — a different demuxer",
        },
        Fixture {
            label: "h264_mkv",
            ext:   "mkv",
            args:  &["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "same bitstream, Matroska — timestamps in ms, not 90 kHz",
        },
        Fixture {
            label: "h265_mp4",
            ext:   "mp4",
            args:  &["-c:v", "libx265", "-pix_fmt", "yuv420p", "-crf", "20"],
            why:   "HEVC, whose extradata (hvcC) differs from H.264's avcC",
        },
        Fixture {
            label: "vp9_webm",
            ext:   "webm",
            args:  &["-c:v", "libvpx-vp9", "-pix_fmt", "yuv420p", "-crf", "30", "-b:v", "0"],
            why:   "VP9 in WebM — no extradata at all, and an alt-ref frame model",
        },
        Fixture {
            label: "vp9_mkv",
            ext:   "mkv",
            args:  &["-c:v", "libvpx-vp9", "-pix_fmt", "yuv420p", "-crf", "30", "-b:v", "0"],
            why:   "VP9 in full Matroska rather than the WebM subset",
        },
        Fixture {
            label: "av1_mkv",
            ext:   "mkv",
            args:  &["-c:v", "libsvtav1", "-pix_fmt", "yuv420p", "-crf", "40"],
            why:   "AV1, the newest codec the decoder must not choke on",
        },
        Fixture {
            label: "prores_mov",
            ext:   "mov",
            args:  &["-c:v", "prores_aw", "-profile:v", "2", "-pix_fmt", "yuv422p10le"],
            why:   "4:2:2 TEN-BIT — takes the swscale conversion path, not passthrough",
        },
        Fixture {
            label: "dnxhr_mov",
            ext:   "mov",
            args:  &["-c:v", "dnxhd", "-profile:v", "dnxhr_lb", "-pix_fmt", "yuv422p"],
            why:   "4:2:2 8-bit intra — also a conversion, at a different depth",
        },
    ];

    /// Whether `NEXIR_REQUIRE_COMPAT` demands that everything actually run.
    fn require() -> bool {
        std::env::var("NEXIR_REQUIRE_COMPAT")
            .map(|v| v != "0" && !v.is_empty())
            .unwrap_or(false)
    }

    /// Locate an `ffmpeg` binary, or explain why the matrix cannot run.
    ///
    /// Delegates to [`crate::bench_media::ffmpeg_binary`], which is the single
    /// locator for the tree — `src/bin/bench.rs` needs the same one and cannot see
    /// a `#[cfg(test)]` module, so the implementation moved there rather than
    /// being duplicated. The `NEXIR_FFMPEG` override and the "missing ffmpeg is a
    /// printed skip, never a pass" contract are unchanged.
    fn ffmpeg_binary() -> Option<PathBuf> {
        crate::bench_media::ffmpeg_binary()
    }

    /// A scratch directory unique to this process, so two concurrent `cargo test`
    /// runs cannot share fixtures.
    fn scratch_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("nexir_compat_{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("failed to create the fixture directory");
        dir
    }

    /// Encode one fixture with `ffmpeg`, returning its path.
    ///
    /// `Err(reason)` means this ffmpeg build cannot produce that codec — a
    /// per-row skip, not a failure, unless `NEXIR_REQUIRE_COMPAT` is set. The
    /// distinction matters: "your ffmpeg lacks libsvtav1" is a property of the
    /// host, whereas "we could not decode the AV1 file we just wrote" is a
    /// property of this crate, and only the second should fail the suite.
    fn write_fixture(ffmpeg: &Path, dir: &Path, f: &Fixture) -> Result<PathBuf, String> {
        let out = dir.join(format!("{}.{}", f.label, f.ext));
        let _ = std::fs::remove_file(&out);

        // `testsrc2` rather than a flat colour: it has motion and detail, so an
        // inter-frame codec produces real P/B frames and a seek has something to
        // land on.  Pixel VALUES are deliberately not asserted anywhere in this
        // file — `export_validation` owns pixel correctness, and asserting it
        // here would mean re-deriving each codec's own loss.
        let source = format!("testsrc2=size={W}x{H}:rate={FPS}:duration={SECONDS}");

        let mut cmd = Command::new(ffmpeg);
        cmd.args(["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i"])
            .arg(&source)
            .args(f.args)
            .arg(&out);

        let output = cmd
            .output()
            .map_err(|e| format!("could not run ffmpeg: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!(
                "ffmpeg could not encode it ({}): {}",
                output.status,
                stderr.lines().last().unwrap_or("(no stderr)").trim()
            ));
        }
        let size = std::fs::metadata(&out)
            .map_err(|e| format!("ffmpeg reported success but the file is unreadable: {e}"))?
            .len();
        if size < 1024 {
            return Err(format!("ffmpeg produced an implausible {size}-byte file"));
        }
        Ok(out)
    }

    /// What one fixture's import + decode reported.
    struct Probed {
        /// Frames obtained, in decode order.
        frames: usize,
        /// PTS of each decoded frame, in the order the decoder emitted them.
        pts: Vec<i64>,
        /// Dimensions the container advertised.
        container_size: (u32, u32),
        /// Dimensions the decoder actually produced.
        decoded_size: (u32, u32),
        /// The layout the decoder wrote, which is what `YuvUploadNode` keys off.
        layout: crate::timeline::source::FrameLayout,
        /// The resolved colour description.
        color: crate::timeline::source::ColorInfo,
        /// Frame rate the container reported, if any.
        frame_rate: Option<Rational>,
    }

    /// Decode up to `max` frames of `path` with this crate's own demuxer/decoder.
    ///
    /// Software decode (`open_sw`): a hardware decoder would hand back NV12 or an
    /// opaque CUDA surface, so the layout assertions would describe the GPU rather
    /// than the file. The import path being tested is the same either way.
    ///
    /// The drain loop is not optional. `open_sw` enables frame-level threading
    /// (`avcodec_set_thread_count(ctx, 0)`), which holds back roughly one frame
    /// per core — a 60-frame fixture can yield nothing at all from the
    /// send/receive loop on a machine with enough cores.
    fn probe_decode(path: &Path, max: usize) -> Result<Probed, String> {
        let mut demuxer =
            Demuxer::open(path).map_err(|e| format!("Demuxer::open failed: {e:?}"))?;
        let stream = demuxer
            .video_stream
            .clone()
            .ok_or_else(|| "the container reports no video stream".to_string())?;

        let cw = stream.width.ok_or("the stream has no width")?;
        let ch = stream.height.ok_or("the stream has no height")?;

        let mut decoder = Decoder::open_sw(&stream, stream.codecpar)
            .map_err(|e| format!("Decoder::open_sw failed: {e:?}"))?;

        // Room for 4:4:4 16-bit at this size, so no fixture's format can overflow
        // the staging buffer regardless of what the decoder chooses.
        let mut buf = vec![0u8; (cw as usize * ch as usize) * 6 + 256];

        let mut pts = Vec::new();
        let mut last: Option<(crate::timeline::source::FrameLayout,
                             crate::timeline::source::ColorInfo,
                             (u32, u32))> = None;

        while pts.len() < max {
            match demuxer.next_video_packet() {
                Ok(Some(pkt)) => match decoder.decode_into(&pkt, &mut buf, None) {
                    Ok(Some(frame)) => {
                        pts.push(frame.pts);
                        last = Some((frame.meta.layout, frame.meta.color,
                                     (frame.width, frame.height)));
                    }
                    Ok(None) => continue,
                    Err(e) => return Err(format!("decode_into failed: {e:?}")),
                },
                Ok(None) => break,
                Err(e) => return Err(format!("next_video_packet failed: {e:?}")),
            }
        }
        while pts.len() < max {
            match decoder.drain_into(&mut buf) {
                Ok(Some(frame)) => {
                    pts.push(frame.pts);
                    last = Some((frame.meta.layout, frame.meta.color,
                                 (frame.width, frame.height)));
                }
                Ok(None) => break,
                Err(e) => return Err(format!("drain_into failed: {e:?}")),
            }
        }

        let (layout, color, decoded_size) =
            last.ok_or("the file produced no decodable frames")?;

        Ok(Probed {
            frames: pts.len(),
            pts,
            container_size: (cw, ch),
            decoded_size,
            layout,
            color,
            frame_rate: stream.frame_rate,
        })
    }

    /// Seek to roughly the middle of `path` and decode one frame there.
    ///
    /// Returns `(landed, target, stream_timebase)`, all in the STREAM's own
    /// timebase, so the caller can rescale the landing into project ticks without
    /// reopening the file — `Demuxer` implements `Drop`, so its `video_stream`
    /// cannot be moved out of a temporary.
    ///
    /// `seek_to` is documented to return the first frame at or after the target,
    /// so the caller asserts a bound rather than equality: a seek goes to a
    /// keyframe and then scans forward, and demanding an exact landing would be
    /// asserting that every fixture has a keyframe at that instant.
    fn probe_seek(path: &Path, target_pts: i64) -> Result<(i64, i64, Rational), String> {
        let mut demuxer =
            Demuxer::open(path).map_err(|e| format!("Demuxer::open failed: {e:?}"))?;
        let stream = demuxer
            .video_stream
            .clone()
            .ok_or_else(|| "no video stream".to_string())?;
        let stream_tb = stream.time_base;
        let mut decoder = Decoder::open_sw(&stream, stream.codecpar)
            .map_err(|e| format!("Decoder::open_sw failed: {e:?}"))?;

        let stream_target = demuxer
            .seek(target_pts, TB)
            .map_err(|e| format!("Demuxer::seek failed: {e:?}"))?;

        match decoder.seek_to(&mut demuxer, stream_target) {
            Ok(landed) => Ok((landed, stream_target, stream_tb)),
            // `NoFrame` means the discard loop hit EOF before the target.  For a
            // fixture whose middle is comfortably inside its duration that is a
            // real failure, so it is reported rather than swallowed.
            Err(DecodeError::NoFrame) => Err(format!(
                "seek_to reached EOF before the target ({stream_target} in stream \
                 ticks) — the seek overshot the file"
            )),
            Err(e) => Err(format!("seek_to failed: {e:?}")),
        }
    }

    /// P2.3 — every codec/container in the matrix must import, decode and seek.
    ///
    /// One test rather than nine, because the fixtures share an ffmpeg probe and a
    /// scratch directory and the interesting output is the TABLE: a per-row PASS or
    /// SKIP line, then a summary. Nine separate tests would each pay for the
    /// ffmpeg lookup and would report a missing encoder nine times.
    ///
    /// Asserted per row that actually ran:
    ///
    /// * **Import** — the container reports the geometry it was written with, and a
    ///   frame rate.
    /// * **Decode** — at least most of the frames come back, at the size the
    ///   container advertised, in a layout `YuvUploadNode` understands (8-bit
    ///   planar, 10-bit planar, NV12 or P010 — never something the upload path
    ///   would silently mis-stride).
    /// * **Timestamps** — PTS is strictly increasing in DECODE order for the
    ///   intra-only codecs and non-decreasing overall. Reordering codecs legally
    ///   emit frames in presentation order after the decoder reorders them, so the
    ///   strict form is asserted only where it is guaranteed.
    /// * **Seek** — landing within a reasonable window of the request rather than
    ///   at zero, which is what a seek that silently rewound to the first keyframe
    ///   would produce.
    /// * **Timeline registration** — the file goes into a `SourceRegistry` with
    ///   `VideoStreamInfo` the scheduler can read back.
    ///
    /// NOT asserted: pixel values. `export_validation` owns that end-to-end, and
    /// deriving per-codec expected pixels here would mean encoding this test's
    /// tolerance to nine different codecs' loss characteristics.
    #[test]
    fn media_compatibility_matrix_imports_decodes_and_seeks() {
        use crate::timeline::source::{
            PixelFormat, SourceRegistry, VideoRotation, VideoStreamInfo,
        };

        let ffmpeg = match ffmpeg_binary() {
            Some(p) => p,
            None => {
                let reason = "no `ffmpeg` binary on PATH (set NEXIR_FFMPEG to \
                              point at one). The linked FFmpeg DLLs do not imply \
                              the CLI is installed.";
                assert!(
                    !require(),
                    "NEXIR_REQUIRE_COMPAT is set but {reason}"
                );
                eprintln!(
                    "[media_compat] SKIP the whole matrix: {reason} No codec or \
                     container was exercised."
                );
                return;
            }
        };

        let dir = scratch_dir();
        let expected_frames = (SECONDS * FPS) as usize;

        let mut ran = 0usize;
        let mut skipped: Vec<(&str, String)> = Vec::new();

        for f in FIXTURES {
            let path = match write_fixture(&ffmpeg, &dir, f) {
                Ok(p) => p,
                Err(why) => {
                    assert!(
                        !require(),
                        "NEXIR_REQUIRE_COMPAT is set but the {} fixture could not \
                         be created: {why}",
                        f.label
                    );
                    eprintln!(
                        "[media_compat] SKIP {:<11} ({}) — {why}. This codec was \
                         NOT exercised.",
                        f.label, f.ext
                    );
                    skipped.push((f.label, why));
                    continue;
                }
            };

            // ── Import + decode ─────────────────────────────────────────────────
            // `expected_frames + 8` so a decoder that emits MORE frames than the
            // file holds is visible as an over-count rather than silently capped.
            let probed = probe_decode(&path, expected_frames + 8)
                .unwrap_or_else(|e| {
                    panic!(
                        "{}: {} — this crate could not read a file its own \
                         linked FFmpeg just wrote, so the format is genuinely \
                         unsupported on the import path. Fixture kept at {}",
                        f.label, e, path.display()
                    )
                });

            assert_eq!(
                probed.container_size, (W, H),
                "{}: the container reports {:?} but the fixture was written at \
                 {W}x{H}",
                f.label, probed.container_size
            );
            assert_eq!(
                probed.decoded_size, (W, H),
                "{}: the decoder produced {:?} frames from a {W}x{H} file — the \
                 upload path would read the wrong stride",
                f.label, probed.decoded_size
            );
            assert!(
                probed.frame_rate.is_some(),
                "{}: the container reported no frame rate, so the scheduler has \
                 nothing to quantise source timestamps against",
                f.label
            );

            // Frame count: allow a shortfall of one, because a codec with an
            // open GOP can legitimately drop a leading frame the container
            // describes, but not a wholesale loss.
            assert!(
                probed.frames + 1 >= expected_frames && probed.frames <= expected_frames + 1,
                "{}: decoded {} frame(s) from a {SECONDS}s {FPS} fps file, \
                 expected {expected_frames} — frames are being lost or duplicated \
                 on import",
                f.label, probed.frames
            );

            // Layout the upload path can actually consume.  This is the assertion
            // that catches a 4:2:2 or 4:4:4 source falling through
            // `frame_layout_for_pix_fmt` into a format `YuvUploadNode` would
            // mis-stride: the decoder is supposed to convert those to planar 4:2:0
            // at the source's own depth.
            let l = probed.layout;
            assert!(
                matches!(l.bit_depth, 8 | 10 | 12),
                "{}: the decoder reported a {}-bit layout, which no upload path \
                 handles",
                f.label, l.bit_depth
            );
            assert!(
                l.bit_depth > 8 || !l.msb_aligned,
                "{}: an 8-bit layout cannot be MSB-aligned",
                f.label
            );

            // ── Timestamps ──────────────────────────────────────────────────────
            assert!(
                !probed.pts.is_empty(),
                "{}: no timestamps were recorded",
                f.label
            );
            for (i, w) in probed.pts.windows(2).enumerate() {
                assert!(
                    w[1] >= w[0],
                    "{}: PTS went backwards between decoded frames {i} and {}: \
                     {} then {}. The decoder emits frames in PRESENTATION order, \
                     so this is not B-frame reordering — it is a timestamp bug.",
                    f.label, i + 1, w[0], w[1]
                );
            }
            let distinct = {
                let mut v = probed.pts.clone();
                v.sort_unstable();
                v.dedup();
                v.len()
            };
            assert_eq!(
                distinct, probed.pts.len(),
                "{}: {} of {} decoded frames share a timestamp — the timeline \
                 would collapse them onto the same instant",
                f.label, probed.pts.len() - distinct, probed.pts.len()
            );

            // ── Seek ────────────────────────────────────────────────────────────
            // Target the middle of the file in project ticks.
            let mid_pts = (SECONDS as i64 * TB.den) / 2;
            let (landed, target, stream_tb) = probe_seek(&path, mid_pts)
                .unwrap_or_else(|e| panic!("{}: {}", f.label, e));
            assert!(
                landed >= target,
                "{}: seek_to returned {landed} for a target of {target} — it is \
                 documented to return the first frame at or AFTER the target",
                f.label
            );
            // Landing must be near the request, not back at the start.  One
            // second of slack covers any keyframe interval these fixtures use
            // (x264 defaults to 250, but a 60-frame file has one GOP, so the
            // forward scan does the work).
            let landed_project = stream_tb.rescale_pts(landed, TB);
            assert!(
                (landed_project - mid_pts).abs() <= TB.den,
                "{}: a seek to {:.3}s landed at {:.3}s — more than a second away, \
                 which is a seek that rewound rather than one that scanned forward",
                f.label,
                mid_pts as f64 / TB.den as f64,
                landed_project as f64 / TB.den as f64
            );

            // ── Timeline registration ───────────────────────────────────────────
            // The last hop before the scheduler: the file has to become a
            // `VideoStreamInfo` that reads back intact.
            let mut reg = SourceRegistry::new();
            let id = reg.register(
                path.clone(),
                Some(VideoStreamInfo {
                    width:        probed.container_size.0,
                    height:       probed.container_size.1,
                    frame_rate:   probed.frame_rate.unwrap(),
                    pixel_fmt:    if l.bit_depth > 8 {
                        PixelFormat::Yuv420p10
                    } else {
                        PixelFormat::Yuv420p
                    },
                    color_info:   probed.color,
                    duration_pts: SECONDS as i64 * TB.den,
                    is_vfr:       false,
                    time_base:    TB,
                    rotation:     VideoRotation::None,
                }),
                None,
            );
            let info = reg
                .video_info(id)
                .unwrap_or_else(|e| panic!("{}: video_info failed: {e:?}", f.label));
            assert_eq!(
                (info.width, info.height), (W, H),
                "{}: the registry round-tripped the wrong dimensions",
                f.label
            );
            assert!(
                reg.is_available(id),
                "{}: a file that exists on disk registered as unavailable",
                f.label
            );
            // `ColorInfo` must be fully resolved by the time it is stored — an
            // `Unknown` reaching the render graph is what `luma_coefficients`
            // silently defaults to BT.709.
            assert_ne!(
                info.color_info.effective_matrix(W, H),
                crate::timeline::source::MatrixCoefficients::Unknown,
                "{}: the stored colour matrix is still Unknown",
                f.label
            );

            eprintln!(
                "[media_compat] PASS {:<11} {:>4}  {} frame(s), {}x{}, {:?}, \
                 {}-bit{}, matrix {:?}, seek {:.3}s→{:.3}s   [{}]",
                f.label, f.ext, probed.frames, W, H,
                probed.frame_rate.unwrap(),
                l.bit_depth,
                if l.semi_planar { " semi-planar" } else { " planar" },
                info.color_info.effective_matrix(W, H),
                mid_pts as f64 / TB.den as f64,
                landed_project as f64 / TB.den as f64,
                f.why,
            );
            ran += 1;
            let _ = std::fs::remove_file(&path);
        }

        eprintln!(
            "[media_compat] matrix: {ran}/{} row(s) exercised",
            FIXTURES.len()
        );
        for (label, why) in &skipped {
            eprintln!("[media_compat]   not exercised: {label} — {why}");
        }
        let _ = std::fs::remove_dir_all(&dir);

        // H.264/MP4 is the one row whose absence means something is wrong with the
        // host rather than with an exotic codec: every ffmpeg build has libx264 or
        // an equivalent, and this crate's own export tests write H.264/MP4.
        assert!(
            ran > 0,
            "not one row of the compatibility matrix ran, though ffmpeg was found \
             — the fixture generation is broken rather than a codec being missing"
        );
    }
}
