[package]
name = "ui"
version.workspace = true
edition = "2024"

[dependencies]
nexir = { path = "../" }
winit = { version = "0.29.15", features = ["rwh_06"] }
egui = "0.27.2"
egui-wgpu = "0.27.2"
egui-winit = "0.27.2"
wgpu = { version = "0.19.4", features = ["wgsl"] }
pollster = "0.3"
log = "0.4"
env_logger = "0.11"
rfd = "0.14"
bytemuck = { version = "1", features = ["derive"] }
serde_json = "1"
num_cpus = "1.16"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "bmp", "tiff"] }
half = "2"
semver = "=1.0.28"
self_update = { version = "=0.42.0", default-features = false, features = ["archive-zip", "compression-zip-deflate", "rustls"] }
